---
- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ home_dir }}/.oh-my-zsh/oh-my-zsh.sh"

- name: Install Starship prompt
  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes
  args:
    creates: /usr/local/bin/starship

- name: Set zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
