---
- name: Install SDKMAN
  ansible.builtin.shell: curl -s "https://get.sdkman.io?rcupdate=false" | bash
  args:
    creates: "{{ home_dir }}/.sdkman/bin/sdkman-init.sh"
  environment:
    SDKMAN_DIR: "{{ home_dir }}/.sdkman"

- name: Install Gradle via SDKMAN
  ansible.builtin.shell: |
    source {{ home_dir }}/.sdkman/bin/sdkman-init.sh && sdk install gradle
  args:
    executable: /bin/bash
    creates: "{{ home_dir }}/.sdkman/candidates/gradle/current/bin/gradle"
