dockutil:
  - { name: "Telegram Desktop",                    path: "/Applications/Telegram Desktop.app" }
  - { name: "Citrix Workspace",                    path: "/Applications/Citrix Workspace.app" }
  - { name: "Spotify",                             path: "/Applications/Spotify.app" }
  - { name: "Obsidian",                            path: "/Applications/Obsidian.app" }
  - { name: "IntelliJ IDEA CE",                    path: "/Applications/IntelliJ IDEA CE.app" }
  - { name: "Visual Studio Code",                  path: "/Applications/Visual Studio Code.app" }
  - { name: "Microsoft Teams (work or school)",    path: "/Applications/Microsoft Teams (work or school).app" }
  - { name: "Microsoft Outlook",                   path: "/Applications/Microsoft Outlook.app" }
  - { name: "Webex",                               path: "/Applications/Webex.app" }
  - { name: "Firefox",                             path: "/Applications/Firefox.app" }
  - { name: "DuckDuckGo",                          path: "/Applications/DuckDuckGo.app" }
  - { name: "iTerm",                               path: "/Applications/iTerm.app" }
  - { name: "KeePassXC",                           path: "/Applications/KeePassXC.app" }
