# basic config
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# theme
set -g @plugin 'arcticicestudio/nord-tmux'

# proper mouse scrolling support
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g mouse on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
# Enable OSC 8 hyperlink support (allows URLs to remain clickable even when wrapped across lines)
set -as terminal-features ",*:hyperlinks"

# Automatically update tmux's environment with these variables
set -g update-environment "SSH_AUTH_SOCK SSH_AGENT_PID"

run '~/.config/tmux/plugins/tpm/tpm'
